export const SET_USER = 'SET_USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ON_LOGIN_FORM_FIELD_CHANGE = 'ON_LOGIN_FORM_FIELD_CHANGE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const ON_REGISTER_FORM_FIELD_CHANGE = 'ON_REGISTER_FORM_FIELD_CHANGE';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';
export const COMMENT_SAVED = 'COMMENT_SAVED';
export const SAVING_COMMENT = 'SAVING_COMMENT';

export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';

export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';
export const COMPANY_FAILURE = 'COMPANY_FAILURE';
export const SET_COMPANY_SERVICE = 'SET_COMPANY_SERVICE';


export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';

export const SERVICE_REQUEST = 'SERVICE_REQUEST';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_FAILURE = 'SERVICE_FAILURE';

export const TIMING_REQUEST = 'TIMING_REQUEST';
export const TIMING_SUCCESS = 'TIMING_SUCCESS';
export const TIMING_FAILURE = 'TIMING_FAILURE';

export const APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST';
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';
export const APPOINTMENT_FAILURE = 'APPOINTMENT_FAILURE';